### ISSUE TITLE
Community Map Website does not mention Easy / Standard Mode

### ISSUE THREAD

**Issue by Sophilautia** [FortuneStreetModding/fortunestreetmodding.github.io#40]
Please add some indicator on the website whether a map is Easy or Standard mode. Yes there are people that look for custom Easy Mode maps.

**Comment by Deflaktor** [comment]
Added a table view with 1ad5a546e83ac5ca0488783100690569fad4746b 
I.e. https://fortunestreetmodding.github.io/mapsTable
