### ISSUE TITLE
[Feature Request] Improve Website Navigation

### ISSUE THREAD

**Issue by Sophilautia** [FortuneStreetModding/fortunestreetmodding.github.io#48]
Some kind of navigation bar for the website would be a great start.

Another would be fleshing out the home page more, to include links to relevant guides etc. And an introduction to what this website even is.

**Comment by MysticMismagius** [comment]
At the very least each page on the site should have a “return to home” button

**Comment by Sophilautia** [comment]
Links to the home page added! But things could still use work.

**Comment by MysticMismagius** [comment]
The [calculator page](https://fortunestreetmodding.github.io/calculator) does not have a Home button.

Also, the social media link buttons (Youtube Channel, Discord, and Github) should ideally open the links in a new tab because there isn't a way to easily navigate back to the site from there
