### ISSUE TITLE
[Feature Request] Order boards by date uploaded on table

### ISSUE THREAD

**Issue by Sophilautia** [FortuneStreetModding/fortunestreetmodding.github.io#52]
Help people find the newest boards easy

**Comment by MysticMismagius** [comment]
There should probably be options for this. There's a valid reason to want the boards to be ordered alphabetically, the way it currently is, and a valid reason to want boards ordered by upload date.

**Comment by Sophilautia** [comment]
Sorry for the confusion, I meant have a sort option on the table view. It wouldn't replace the existing order of the cards view.

**Comment by Deflaktor** [comment]
Boards are now sorted by last update date
